# -*- coding: utf-8 -*-
"""LAB-4ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3Wx5LGABtf6G-fx5wZ8_rqvYjIt40o_
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
          'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
              'DOB': ['1990-05-15', '1985-10-22', '1992-07-08', '1988-03-25', '1995-12-30'],
                  'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
                      'Salary': [70000, 80000, 75000, 90000, 65000]
                      }

df = pd.DataFrame(data)

df['DOB'] = pd.to_datetime(df['DOB'])
df['Age'] = pd.Timestamp.now().year - df['DOB'].dt.year

label_encoder = LabelEncoder()
df['Gender_Label'] = label_encoder.fit_transform(df['Gender'])

df = pd.get_dummies(df, columns=['City'])

grouped_df = df.groupby('Gender')['Salary'].mean().reset_index()
print("Average Salary by Gender:")
print(grouped_df)

pivot_df = df.pivot_table(values='Salary', index='Gender', columns='Age', aggfunc='mean', fill_value=0)
print("\nPivot Table (Salary by Gender and Age):")
print(pivot_df)

print("\nTransformed DataFrame:")
print(df)